"""Run from the repository root: python -m unittest discover -s tests -v"""
import csv
import json
import math
import os
import sys
import tempfile
import unittest
from dataclasses import replace

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import chatbot_auction as ca  # noqa: E402

with open(os.path.join(ROOT, "tests", "js_fixture.json"), encoding="utf-8") as fh:
    JS = json.load(fh)


class ParityWithHuggingFaceGame(unittest.TestCase):
    """Fixture generated by the game's game_logic.js (Node), so both artifacts share one model."""

    def test_config_matches_game(self):
        c = JS["config"]
        b = ca.BASELINE
        self.assertEqual(
            (b.n, b.cost_max, b.cap, b.engagement_gain, b.extra_tuning_cost, b.audit_prob, b.fine, b.rounds_per_rule),
            (c["N"], c["COST_MAX"], c["CAP"], c["ENGAGEMENT_GAIN"], c["EXTRA_TUNING_COST"], c["AUDIT_PROB"],
             c["FINE"], c["ROUNDS_PER_RULE"]))

    def test_seeds_and_generator(self):
        for code, seed in JS["seeds"].items():
            self.assertEqual(ca.seed_from_code(code), seed)
        rng = ca.mulberry32(12345)
        self.assertEqual([rng() for _ in JS["rng"]], JS["rng"])

    def test_schedules(self):
        for code, sched in JS["schedules"].items():
            self.assertEqual(ca.make_schedule(code), sched)

    def test_benchmark_bids(self):
        for cost, rule, bid in JS["benchmarks"]:
            self.assertEqual(ca.benchmark_bid(cost, rule), bid, (cost, rule))

    def test_resolved_rounds(self):
        sched = ca.make_schedule("206")
        bids = [r["playerBid"] for r in JS["rounds"]]
        cheats = [r["winner"] == 0 and r["cheated"] for r in JS["rounds"]]
        mine = [ca.resolve_round(r, b, c) for r, b, c in zip(sched["rounds"], bids, cheats)]
        self.assertEqual(mine, JS["rounds"])


class Theory(unittest.TestCase):
    def test_audit_threshold(self):
        self.assertAlmostEqual(ca.audit_threshold(ca.BASELINE), 0.4)
        self.assertAlmostEqual(ca.expected_cheat_value(ca.BASELINE), -5)
        self.assertFalse(ca.rational_cheats(ca.BASELINE))
        self.assertTrue(ca.rational_cheats(replace(ca.BASELINE, audit_prob=0.3)))
        self.assertFalse(ca.rational_cheats(replace(ca.BASELINE, audit_prob=0.4)))

    def test_first_price_closed_form(self):
        # b(40) = 40 + (60^4 - 20^4) / (4 * 60^3)
        self.assertAlmostEqual(ca.benchmark_bid_exact(40, "first", ca.BASELINE), 40 + (60**4 - 20**4) / (4 * 60**3))
        self.assertAlmostEqual(ca.benchmark_bid_exact(80, "first", ca.BASELINE), 80)
        prev = -math.inf
        for i in range(160):
            c = i / 2
            b = ca.benchmark_bid_exact(c, "first", ca.BASELINE)
            self.assertTrue(prev <= b <= ca.BASELINE.cap and b > c - 1e-12)
            prev = b

    def test_rent_shades_bids(self):
        weak = replace(ca.BASELINE, audit_prob=0.3)  # rent = 20 - 15 = 5
        self.assertAlmostEqual(ca.cheating_rent(weak), 5)
        self.assertAlmostEqual(ca.benchmark_bid_exact(40, "second", weak), 35)
        self.assertEqual(ca.benchmark_bid_exact(3, "second", weak), 0)
        self.assertLess(ca.benchmark_bid_exact(40, "first", weak), ca.benchmark_bid_exact(40, "first", ca.BASELINE))

    def test_second_price_truthful_is_weakly_dominant(self):
        grid = list(range(0, 101, 5))
        for cost in (5, 25, 50, 75, 79, 85):
            for r1 in grid:
                for r2 in grid:
                    bids_others = [r1, r2, 100]

                    def payoff(bid):
                        w, pay = ca.run_auction([bid] + bids_others, "second", ca.BASELINE.cap, rounding=False)
                        return ca.round_profit(w == 0, pay, cost, False, False, rounding=False)

                    truthful = payoff(cost)
                    for dev in grid:
                        self.assertGreaterEqual(truthful, payoff(dev) - 1e-9)

    def test_first_price_benchmark_is_best_response(self):
        cfg = ca.BASELINE
        rng = ca.mulberry32(7)
        draws = [[rng() * cfg.cost_max for _ in range(cfg.n - 1)] for _ in range(40000)]
        rival_bids = [[ca.benchmark_bid_exact(c, "first", cfg) for c in d] for d in draws]
        for cost in (20, 40, 60):
            b = ca.benchmark_bid_exact(cost, "first", cfg)

            def expected_profit(bid):
                total = 0.0
                for rb in rival_bids:
                    if bid <= cfg.cap and bid < min(rb):
                        total += bid - cost
                return total / len(rival_bids)

            base = expected_profit(b)
            for dev in (b - 5, b - 2, min(cfg.cap, b + 2), min(cfg.cap, b + 5)):
                self.assertGreaterEqual(base, expected_profit(dev), (cost, dev))

    def test_revenue_equivalence(self):
        exact = ca.expected_spending_exact(ca.BASELINE)
        self.assertAlmostEqual(exact, 39.7312, places=3)
        comp = ca.compare_rules(ca.BASELINE, trials=50000, seed=206)
        for rule in ca.RULES:
            se = comp[rule]["sd_spending"] / math.sqrt(50000)
            self.assertLess(abs(comp[rule]["mean_spending"] - exact), 4 * se, rule)
        self.assertLess(comp["first"]["sd_spending"], comp["second"]["sd_spending"])


class Rules(unittest.TestCase):
    def test_auction_outcomes(self):
        self.assertEqual(ca.run_auction([30, 50, 40, 90], "second", 80), (0, 40))
        self.assertEqual(ca.run_auction([30, 50, 40, 90], "first", 80), (0, 30))
        self.assertEqual(ca.run_auction([30, 85, 90, 95], "second", 80), (0, 80))
        self.assertEqual(ca.run_auction([85, 81, 90, 95], "second", 80), (-1, 0.0))
        self.assertEqual(ca.run_auction([40, 40, 60, 70], "first", 80), (0, 40))

    def test_invalid_inputs(self):
        for bids in ([math.nan, 40], [-1, 40], [101, 40], [True, 40], [40]):
            with self.assertRaises(ValueError):
                ca.run_auction(bids, "second", 80)
        with self.assertRaises(ValueError):
            ca.run_auction([10, 20], "third", 80)
        for bad in ({"audit_prob": 1.5}, {"n": 1}, {"cap": 120}, {"fine": -1}, {"cap": math.inf},
                    {"cap": 90, "audit_prob": 0.0}):
            with self.assertRaises(ValueError):
                replace(ca.BASELINE, **bad)

    def test_profit_and_efficiency(self):
        self.assertEqual(ca.round_profit(True, 60, 40, False, False), 20)
        self.assertEqual(ca.round_profit(True, 60, 40, True, False), 40)
        self.assertEqual(ca.round_profit(True, 60, 40, True, True), -10)
        self.assertEqual(ca.round_profit(False, 60, 40, True, True), 0)
        self.assertTrue(ca.is_efficient([10, 20, 30], 0, 80))
        self.assertFalse(ca.is_efficient([10, 20, 30], 1, 80))
        self.assertTrue(ca.is_efficient([90, 95], -1, 80))
        self.assertFalse(ca.is_efficient([90, 50], -1, 80))

    def test_simulation_is_deterministic(self):
        a = ca.simulate("first", trials=2000, seed=1)
        b = ca.simulate("first", trials=2000, seed=1)
        self.assertEqual(a, b)

    def test_weak_audit_lowers_spending_but_loses_honesty(self):
        weak = ca.compare_rules(replace(ca.BASELINE, audit_prob=0.3), trials=5000)
        strong = ca.compare_rules(ca.BASELINE, trials=5000)
        for rule in ca.RULES:
            self.assertEqual(weak[rule]["honest_delivery_rate"], 0)
            self.assertGreater(strong[rule]["honest_delivery_rate"], 0.99)
            self.assertLess(weak[rule]["mean_spending"], strong[rule]["mean_spending"])


class ClassroomRecords(unittest.TestCase):
    def test_reads_game_csv(self):
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "player.csv")
            with open(path, "w", encoding="utf-8", newline="") as fh:
                fh.write(JS["csv"])
            with open(path, newline="", encoding="utf-8") as fh:
                rows = list(csv.DictReader(fh))
            self.assertEqual(rows[0]["note"], 'test, with "quotes"')
            s = ca.summarize_classroom([path])
            self.assertEqual(s["rounds"], 6)
            self.assertEqual(s["first"]["player_wins"], 1)
            self.assertEqual(s["first"]["player_cheat_rate"], 1.0)
            self.assertEqual(s["second"]["player_cheat_rate"], 0.0)


class NotebookParity(unittest.TestCase):
    def test_notebook_embeds_this_module(self):
        nb_path = os.path.join(ROOT, "PS2_chatbot_subsidy_auction.ipynb")
        with open(nb_path, encoding="utf-8") as fh:
            nb = json.load(fh)
        cell = next(c for c in nb["cells"] if c["cell_type"] == "code"
                    and "".join(c["source"]).startswith("%%writefile chatbot_auction.py"))
        embedded = "".join(cell["source"]).split("\n", 1)[1]
        with open(os.path.join(ROOT, "chatbot_auction.py"), encoding="utf-8") as fh:
            self.assertEqual(embedded.rstrip("\n"), fh.read().rstrip("\n"))


if __name__ == "__main__":
    unittest.main()
